// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTty6h7w3U_WpG2YJ534TNDc6ZlOGJImI',
    appId: '1:955816575532:web:f717b7f0693501e944c789',
    messagingSenderId: '955816575532',
    projectId: 'tiktok-clone-sigirace',
    authDomain: 'tiktok-clone-sigirace.firebaseapp.com',
    storageBucket: 'tiktok-clone-sigirace.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDARM4ejSiy04upnuAk5yyBqYQ7yc90sOc',
    appId: '1:955816575532:android:09b7e3bad92beeb044c789',
    messagingSenderId: '955816575532',
    projectId: 'tiktok-clone-sigirace',
    storageBucket: 'tiktok-clone-sigirace.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZwuBclqlqPGjy8pKHjyeYS7PR9YMIaIw',
    appId: '1:955816575532:ios:45ec02ee364312bc44c789',
    messagingSenderId: '955816575532',
    projectId: 'tiktok-clone-sigirace',
    storageBucket: 'tiktok-clone-sigirace.appspot.com',
    iosBundleId: 'tictokClone',
  );

}